---

- name: install/update curl
  apt: name=curl state=latest

- name: install composer globally
  shell: >
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    creates=/usr/local/bin/composer

- name: update composer
  shell: >
    composer self-update
  register: composer_update
  changed_when: "'Updating to version' in composer_update.stdout"