---

- name: apache | ensure apache mod_rewrite is enable
  action: command a2enmod rewrite
  register: apache_mod_rewrite_enable
  changed_when: "'already enabled' not in apache_mod_rewrite_enable.stdout"
  notify:
    - apache-restart

- name: apache | ensure drupal directory exists
  file: path={{ apache_www_dir }}/{{ drupal_server_name }} state=directory owner={{ apache_user }} group={{ apache_user }} mode=0775

- name: apache | vhost config
  template: src=etc/apache2/sites/available/drupal.conf.j2 dest=/etc/apache2/sites-available/{{ drupal_server_name }}.conf
  notify:
    - apache-reload

- name: apache | disable default vhost
  action: command a2dissite 000-default
  register: apache_disable_vhost
  changed_when: "'already disabled' not in apache_disable_vhost.stdout"
  notify:
    - apache-reload

- name: apache | enable drupal vhost
  action: command a2ensite {{ drupal_server_name }}
  register: apache_enable_vhost
  changed_when: "'already enabled' not in apache_enable_vhost.stdout"
  notify:
    - apache-reload