---

- name: ensure apache mod_rewrite is enable
  action: command a2enmod rewrite
  register: apache_mod_rewrite_enable
  changed_when: "'already enabled' not in apache_mod_rewrite_enable.stdout"
  notify:
    - apache-restart

- name: ensure drupal directory exists
  file: path=/var/www/drupal state=directory owner=www-data group=www-data mode=0775

- name: vhost config
  action: template src=etc-apache2-sites-available-drupal.conf.j2 dest=/etc/apache2/sites-available/drupal.conf
  notify:
    - apache-reload

- name: disable default vhost
  action: command a2dissite 000-default
  register: apache_disable_vhost
  changed_when: "'already disabled' not in apache_disable_vhost.stdout"
  notify:
    - apache-reload

- name: enable drupal vhost
  action: command a2ensite drupal
  register: apache_enable_vhost
  changed_when: "'already enabled' not in apache_enable_vhost.stdout"
  notify:
    - apache-reload