---

- name: drupal-install | copy drush makefile
  copy: src=drupal-site.yml dest={{ apache_www_dir }}/{{ drupal_server_name }}/drupal-site.yml

- name: drupal-install | check lock file
  stat: path={{ apache_www_dir }}/{{ drupal_server_name }}/.installed.lock
  register: drupalLock

- name: drupal-install | run drush make
  command: drush make drupal-site.yml -y chdir={{ apache_www_dir }}/{{ drupal_server_name }}
  when: drupalLock.stat.exists == false

- name: drupal-install | run drush site-install
  command: >
    drush site-install -y
    --account-name={{ drupal_account_name }}
    --account-pass={{ drupal_account_password }}
    --site-name="{{ drupal_site_name }}"
    --db-url=mysql://{{ drupal_db_user }}:{{ drupal_db_password }}@{{ drupal_db_host }}/{{ drupal_db_name }}
    chdir={{ apache_www_dir }}/{{ drupal_server_name }}
  when: drupalLock.stat.exists == false

- name: drupal-install | set permissons
  file: path={{ apache_www_dir }}/{{ drupal_server_name }} state=directory owner={{ apache_user }} group={{ apache_group }} recurse=yes
  when: drupalLock.stat.exists == false

- name: drupal-install | create lock file
  file: path={{ apache_www_dir }}/{{ drupal_server_name }}/.installed.lock state=touch owner={{ apache_user }} group={{ apache_group }}
  when: drupalLock.stat.exists == false