---

- name: ensure /etc/drush directory exists
  file: path=/etc/drush state=directory

- name: symlink php.ini from /etc/php5/apache2/php.ini
  file: >
    src=/etc/php5/apache2/php.ini
    dest=/etc/drush/php.ini
    state=link